// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAEZ89C_onJMmb6J_fVVXxAZU8i1PtVofQ',
    appId: '1:652678497330:web:fb833235630bf76b6ee82b',
    messagingSenderId: '652678497330',
    projectId: 'quotes-app-c4548',
    authDomain: 'quotes-app-c4548.firebaseapp.com',
    storageBucket: 'quotes-app-c4548.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB1ecyix6xC33FL86KayctlLDJg7z8ObYo',
    appId: '1:652678497330:android:019091a67a9e8e6c6ee82b',
    messagingSenderId: '652678497330',
    projectId: 'quotes-app-c4548',
    storageBucket: 'quotes-app-c4548.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC_S7COjR7_dbTVCLdMM29dWuQP6LRwKB0',
    appId: '1:475847233851:ios:3316ec5a5e8d502320271e',
    messagingSenderId: '475847233851',
    projectId: 'quote-demo-d97ed',
    storageBucket: 'quote-demo-d97ed.appspot.com',
    iosBundleId: 'com.example.quotesDemo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC_S7COjR7_dbTVCLdMM29dWuQP6LRwKB0',
    appId: '1:475847233851:ios:3316ec5a5e8d502320271e',
    messagingSenderId: '475847233851',
    projectId: 'quote-demo-d97ed',
    storageBucket: 'quote-demo-d97ed.appspot.com',
    iosBundleId: 'com.example.quotesDemo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAAzXxJ9tB4hu-cVUheYwcZqnQZofEjO28',
    appId: '1:475847233851:web:ad019d2e78e8c9f520271e',
    messagingSenderId: '475847233851',
    projectId: 'quote-demo-d97ed',
    authDomain: 'quote-demo-d97ed.firebaseapp.com',
    storageBucket: 'quote-demo-d97ed.appspot.com',
  );
}